### ISSUE TITLE
New contributor

### ISSUE THREAD

**Issue by jnweiger** [amade/screen#2]
Hey amade!
A friend of mine, Alex Naumov wants to help with maintaining screen.
What is the best way to get in contact? His github id is  @alexander-naumov

thanks, JW

**Comment by mikegerwitz** [comment]
This has been sitting here a while, so I'll reply.

Amade has been appointed as a co-maintainer of GNU screen; [there are many others](https://savannah.gnu.org/projects/screen).  The best place to start would be to begin submitting patches to the project.

You can discuss further on the [`screen-devel`](http://lists.gnu.org/mailman/listinfo/screen-devel) mailing list.  I don't think that this repository is used any more now that it's back in the hands of GNU.
